name: Test Workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Enter the name of the Environment to be deployed on'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  aws_login_test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@5fd3084fc36e372ff1fff382a39b10d03659f355
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1


