name: Test Workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Enter the name of the Environment to be deployed on'
        required: true
        type: string
jobs:
  aws_login_test:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      role_to_assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      aws_region: us-east-1

    steps:
      - run: |
          echo "Role to Assume: ${{ env.role_to_assume }}"
          echo "AWS Region: ${{ env.aws_region }}"
      - name: AWS Login with Secrets
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.role_to_assume }}
          aws-region: ${{ env.aws_region }}


